create or replace PACKAGE BODY PKG_SURVEY AS

  PROCEDURE PROC_HAIR_LIST( 
        IN_FACE_NUM IN NUMBER,
        O_CUR OUT SYS_REFCURSOR ) AS
  BEGIN
    
    OPEN O_CUR FOR
        SELECT  F.FACE_NUM, F.FACE_NAME, H.HAIR_ID, H.HAIR_NAME
          FROM  FACESHAPE F, HAIRS H
         WHERE  F.FACE_NUM = H.FACE_NUM
           AND  F.FACE_NUM = IN_FACE_NUM;
    
  END PROC_HAIR_LIST;

  PROCEDURE PROC_HAIR_VIEW( 
        IN_HAIR_ID  IN VARCHAR2, 
        O_FACE_NAME OUT VARCHAR2,
        O_HAIR_ID   OUT VARCHAR2,
        O_HAIR_NAME OUT VARCHAR2 ) AS
  BEGIN
    
    SELECT  FACE_NAME, HAIR_ID, HAIR_NAME
      INTO  O_FACE_NAME, O_HAIR_ID, O_HAIR_NAME
      FROM  FACESHAPE F, HAIRS H
     WHERE  HAIR_ID = IN_HAIR_ID
       AND  F.FACE_NUM = H.FACE_NUM;
 
  END PROC_HAIR_VIEW;

  PROCEDURE PROC_RESERVE( 
        IN_CID IN VARCHAR2,
        IN_HAIR_NAME IN VARCHAR2, 
        IN_RESDAY IN VARCHAR2 
        ) AS
  BEGIN
    
    UPDATE  CLIENTINFO
       SET  CRESULT = IN_HAIR_NAME,
            RESDAY  = IN_RESDAY
     WHERE  CID = IN_CID;
    COMMIT;
    
  END PROC_RESERVE;

END PKG_SURVEY;